### ISSUE TITLE
Is it possible to add more servers and workstations?

### ISSUE THREAD

**Issue by rajganeshp** [christophetd/Adaz#27]
I see that there are 3 workstations created in this lab? Is it possible to add more workstations? if so, which config file should i change? Also, is it possible to add servers to the mix to join the domain. some documentation along those lines will be helpful.

**Comment by christophetd** [comment]
You can add more workstations by customizing `domain.yml`, see https://github.com/christophetd/Adaz/blob/master/doc/configuration_reference.md

Currently, you cannot add more servers but feel free to detail your use-case!

**Comment by rajganeshp** [comment]
Thank you. good to have servers to the mix to add IIS, Fileserver, PKI,
etc. again, this is great. thanks for developing.

**Comment by christophetd** [comment]
I'll close this issue for now, feel free to reopen if needed!
