### ISSUE TITLE
VPN instead of inbound rules

### ISSUE THREAD

**Issue by k-alshamsi** [christophetd/Adaz#35]
how about VPN in the ES box for example to join the network instead of the NSG rules which might affect the flexibility if you keep connecting from different network.

**Comment by christophetd** [comment]
I agree having an OpenVPN server / Azure VPN Gateway would be nice, but on the other hand it would add non-negligible complexity to the overall setup, so I'd rather not add that for now.

Another option would be to add a boolean setting to:
- Not expose the Windows machines to the Internet
- Use the ES box as a bastion open to anyone on the Internet, to be able to do SSH tunnelling through it

**Comment by christophetd** [comment]
Closing with the rationale it would add too much cost / complexity / time to spin up the lab.
