### ISSUE TITLE
Couldn't get it working, help would be appreciated

### ISSUE THREAD

**Issue by vegworld** [christophetd/Adaz#42]
**What is not working?**

I spent hours already but I can't get it working. 

On my Win10 local machine:
I created an Azure subscription - successfully
Downloaded and installed Azure CLI for Windows (MSI) - successfully 
Opened cmd.exe and then executed az login to connect to my account - successfully
Created an (OpenSSH) SSH key using cmd.exe > ssh-keygen - successfully
opened cmd.exe then executed winget install git.git - successfully
opened Git CMD then executed git clone https://github.com/christophetd/Adaz.git - successfully

I opened a command prompt, navigated to C:\Users\VegWorld\Adaz and then executed python3 -m venv ansible/venv 
that didn't seem to work, so I navigated to \Adaz\ansible and then executed py -m venv env
A folder named env was created inside the folder ansible. I manually renamed it to venv
executed python3 source ansible/venv/bin/activate > no output/error was shown...
Then, I executed pip install -r ansible/requirements.txt which took a lot of time, and it finished with errors. 
What went wrong? help would be greatly appreciated

**What OS are you using?**
Windows 10 

**Your `domain.yml` file?**
If you customized the `domain.yml` file, please include it below

**Full Terraform / Ansible output?**

Search "error" (6 hits in 1 file) (Notepad++)
  (6 hits)
	Line 447: ERROR: msal 1.0.0 has requirement PyJWT[crypto]<2,>=1.0.0, but you'll have pyjwt 2.3.0 which is incompatible.
	Line 448: ERROR: pyopenssl 21.0.0 has requirement cryptography>=3.3, but you'll have cryptography 2.9.2 which is incompatible.
	Line 464:     Running setup.py install for ansible ... error
	Line 465:     ERROR: Command errored out with exit status 1:
	Line 6828:     error: symbolic link privilege not held
	Line 6830: ERROR: Command errored out with exit status 1: 'c:\users\vegworld\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\vegworld\\AppData\\Local\\Temp\\pip-install-q7an93pr\\ansible\\setup.py'"'"'; __file__='"'"'C:\\Users\\vegworld\\AppData\\Local\\Temp\\pip-install-q7an93pr\\ansible\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\vegworld\AppData\Local\Temp\pip-record-5gxbcum5\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\vegworld\appdata\local\programs\python\python37-32\Include\ansible' Check the logs for full command output.

WARNING: You are using pip version 20.0.2; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\vegworld\appdata\local\programs\python\python37-32\python.exe -m pip install --upgrade pip' command.

(I can provide the full text file if needed, too big for GitHub)

**Comment by christophetd** [comment]
On Windows 10, I would suggest using Git Bash or the Windows Subsystem for Linux (WSL). Can you give it a go? The issue seems related to your Python / Pip setup, not to Adaz specifically.

**Comment by vegworld** [comment]
> 

Hi christophe, 
I will install Git Bash.
PIP was updated to 21.3.1. 
Which python version should I use? 

Thank you

**Comment by christophetd** [comment]
Python 3.x should be fine
