### ISSUE TITLE
Maybe SecurityOnion can shorten work effort

### ISSUE THREAD

**Issue by ITfromHell** [christophetd/Adaz#45]
Hi, 
I´m comming here by accident and see a few feature requests because Kibana, Suricata, Sigma rules, ...
Just as hint: Do you know Security Onion? Its an open source Saltstack based system, where ELK, Kibana, Surricata, Sigma rules, ... is integrated to a whole ecosystem.
Maybe this helps you keeping the effort low.
https://github.com/Security-Onion-Solutions/securityonion 
https://docs.securityonion.net/en/2.3/
(I´m not in any relation to SecurityOnion, just a user of)

**Comment by christophetd** [comment]
Thanks for the input! As is it would require too much changes, but we can reconsider if we need to add mahor features where security onion would be helpful!
