### ISSUE TITLE
terraform needs ssh key passphrase, but mixed with terraform output

### ISSUE THREAD

**Issue by mathieuchateau** [christophetd/Adaz#49]
When doing an apply, terraform will prompt for passphrase to access ssh key.

What happens it that terraform does not stop waiting for it, it continues to try provisioning. passphrase request is mixed in the terraform output. If missed, deploy will fail.

example:
![image](https://user-images.githubusercontent.com/4478521/203289747-589b5ad7-bcb5-4175-b90d-84c745954244.png)

Not sure if there is a cleaner way, but a wait would help catch maybe ?
```
- name: Sleep for 30 seconds and continue with play
      wait_for: 
        timeout: 30
```

**Comment by christophetd** [comment]
I'd recommend adding the SSH key to ssh-agent so you can use it without being prompted for a key. Added a note in the readme: https://github.com/christophetd/Adaz/commit/644988994c283b7ef7cb5e17de6689865a241d3f

Can you confirm that works for you?

**Comment by mathieuchateau** [comment]
yes it did the trick thanks
