### ISSUE TITLE
Ansible Domain Controller playbook fails due to outdated pywinrm version

### ISSUE THREAD

**Issue by grim3** [christophetd/Adaz#55]
Macos w/ Python 3.11.5

`TASK [domain-controller : Ensure necessary Microsoft features are installed] *************************************************************************************************************
failed: [domain-controller_4da5] (item=AD-Domain-Services) => {"ansible_loop_var": "item", "item": "AD-Domain-Services", "msg": "ntlm: module 'inspect' has no attribute 'getargspec'", "unreachable": true}
failed: [domain-controller_4da5] (item=RSAT-AD-AdminCenter) => {"ansible_loop_var": "item", "item": "RSAT-AD-AdminCenter", "msg": "ntlm: module 'inspect' has no attribute 'getargspec'", "unreachable": true}
failed: [domain-controller_4da5] (item=RSAT-ADDS-Tools) => {"ansible_loop_var": "item", "item": "RSAT-ADDS-Tools", "msg": "ntlm: module 'inspect' has no attribute 'getargspec'", "unreachable": true}
fatal: [domain-controller_4da5]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"ansible_loop_var": "item", "item": "AD-Domain-Services", "msg": "ntlm: module 'inspect' has no attribute 'getargspec'", "unreachable": true}, {"ansible_loop_var": "item", "item": "RSAT-AD-AdminCenter", "msg": "ntlm: module 'inspect' has no attribute 'getargspec'", "unreachable": true}, {"ansible_loop_var": "item", "item": "RSAT-ADDS-Tools", "msg": "ntlm: module 'inspect' has no attribute 'getargspec'", "unreachable": true}]}`

Upgrade `pywinrm==0.4.1` to `pywinrm==0.4.3` in ansible/requirements.txt

**Comment by christophetd** [comment]
Thanks for flagging! Will try to reproduce and post back here

**Comment by christophetd** [comment]
Was able to reproduce and confirm that this fixes the issue, thanks a lot for reporting!
