### ISSUE TITLE
Error: Error making request: Get "http://ipv4.icanhazip.com": dial tcp 10.25.207.164:80: i/o timeout

### ISSUE THREAD

**Issue by rstar13as** [christophetd/Adaz#57]
**What is not working?**

Error: Error making request: Get "http://ipv4.icanhazip.com": dial tcp 10.25.207.164:80: i/o timeout
│ 
│   with data.http.public_ip,
│   on data.tf line 21, in data "http" "public_ip":
│   21: data "http" "public_ip" {

------
I corrected this by adding the following to data.tf

data "http" "public_ip" {
  url = "https://api.ipify.org"
}

**Comment by christophetd** [comment]
Thanks for reporting! http://ipv4.icanhazip.com/ works for me, can you access it from your browser?

**Comment by rstar13as** [comment]
actually , i can access http://ipv4.icanhazip.com/  now, it was timing out the other day

**Comment by christophetd** [comment]
Most likely a temporary network issue then, will close but feel free to reopen if needed. Thanks!
